// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geektime/layout/internal/biz"
	"geektime/layout/internal/conf"
	"geektime/layout/internal/data"
	"geektime/layout/internal/data/db"
	"geektime/layout/internal/server"
	"geektime/layout/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func initApp(cs *conf.Server, cd *conf.Data) *grpc.Server {
	gormDB := db.NewGormDb(cd)
	client := db.NewClient(gormDB)
	dataData := data.NewData(client)
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGrpcServer(cs, userService)
	return grpcServer
}
