// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"geektime/layout/app/user/service/internal/biz"
	"geektime/layout/app/user/service/internal/data"
	"geektime/layout/app/user/service/internal/server"
	"geektime/layout/app/user/service/internal/service"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func initApp() (*grpc.Server, error) {
	db := data.NewDb()
	dataData := data.NewData(db)
	userRepo := data.NewUserRepo(dataData)
	userUseCase := biz.NewUserUseCase(userRepo)
	userService := service.NewUserService(userUseCase)
	grpcServer := server.NewGrpcServer(userService)
	return grpcServer, nil
}
